### ISSUE TITLE
Create documentation / Prepare for open sourcing

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#24]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jakedavies](https://github.com/Jakedavies)**
_Friday May 18, 2018 at 14:52 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/218_

----

We are looking to open source soon(I assume some time next week). We have been asked to create some documentation.

- [x] Create a repository
- [x] Rename repository, og => cg, DBs, configs, etc.
- [x] Remove boilerplate docs
- [x] Link between README's for subfolders READMEs (under further reading and other `TODO:`) places
- [x] Organize top level README's for a better quick start
- [x] Script / Guide for generating secrets for local development – not good practice to contain even fake secrets in `.env.example`
- [x] OG API documentation - @fjcero 
- [x] Document how to set up quorum for local dev
- [x] Troublshooting/Common problems section - @sindelio 
- [x] Clean up any github stuff that should be cleaned up
- [x] What do we do with internal CT deployment source code (terraform, etc.)?
- [x] URLs on front-end depend on our AWS URL configs.. (``config.CG_API_BASE = `${protocol}//og-${host}`;``) - @Jakedavies
- [x] Cleanup boilerplate code (e2e tests, etc.)
- [x] Remove redis
- [x] Cleanup of obsolete helper scripts in `scripts/` directory
- [x] Architecture diagram - @Jakedavies 
- [x] Remove or fix of Makefiles
- [x] Decide on the license - @Jakedavies 
- [x] Thoroughly test Quick Start Guide @Jakedavies @sindelio @fjcero
- [x] Fix broken tests @Jakedavies 
- [x] Nice looking diagram @juanmnl 
- [x] Generate nice docs using https://docsify.js.org/ @fjcero 

For later:
- [x] Generate wallet private key for the tests (#38, #39)
- [ ] Add a public build / publish process (do we publish images?) (#44)
- [ ] Nice wordpress like installation experience instead of the Quick Start guide (#42)
- [ ] Remove the `test:integration` differentiator and documentation (#45)
- [ ] Document or remove healthchecks (#47)
- [ ] Add coverage badge (included in #44)
- [ ] Document production-ish quorum deployment (#46)

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Monday May 21, 2018 at 13:30 GMT_

----

We have a new repo for this: https://github.com/clevertech/ClearGDPR

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Monday May 21, 2018 at 14:17 GMT_

----

As far as:
**What do we do with internal CT deployment source code (terraform, etc.)?**
I discussed with @mfornasa and we're getting rid of that in favour of a public build/deployment using Travis/Circle/Semaphore/or something like that

**Comment by Jakedavies** [comment]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Jakedavies](https://github.com/Jakedavies)**
_Tuesday May 22, 2018 at 05:21 GMT_

----

Here is the an architecture diagram I did. Its at a pretty high level, I'm open to suggestions on possibly some additional diagrams/changes to this one. 

https://drive.google.com/file/d/1C9c1XvVzCFx5gPrkBsMkCggZKqCzBJ7I/view?usp=sharing

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Tuesday May 22, 2018 at 11:35 GMT_

----

@Jakedavies looks good. I'd only make notes, that CG Server to server communication is over HTTP.
@juanmnl you think you can make it sexier? ;)
I think your look at our docs could add a nice touch.

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Tuesday May 22, 2018 at 13:06 GMT_

----

@juanmnl by sexy I mean the likes of:
https://zenaton.com/documentation?lang=javascript#

<img width="1138" alt="overwiew" src="https://user-images.githubusercontent.com/1215868/40364117-be3be14c-5dd1-11e8-827b-1f51b86eaa38.png">

**Comment by Jakedavies** [comment]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sindelio](https://github.com/sindelio)**
_Tuesday May 22, 2018 at 13:45 GMT_

----

Maybe the arrows from blockchains node 2 and 3 should be bidirectional? blockchains syncs happen both ways

**Comment by Jakedavies** [comment]
<a href="https://github.com/juanmnl"><img src="https://avatars1.githubusercontent.com/u/699945?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [juanmnl](https://github.com/juanmnl)**
_Tuesday May 22, 2018 at 14:30 GMT_

----

@maksymilian-majer is this diagram final? or should I wait for updates and/or fixes?

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Wednesday May 23, 2018 at 13:31 GMT_

----

See testing instructions in #232

**Comment by maksymilian-majer** [comment]
I added follow-up issues for outstanding items on the list.
